# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rDxzI8vnEZnr6CUysbua2EUfrF5xU0Ub
"""

# Import required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set visualization style
sns.set(style="whitegrid")

# Upload file manually in Google Colab
from google.colab import files
uploaded = files.upload()

# Load dataset
file_name = list(uploaded.keys())[0]  # Get the uploaded filename
df = pd.read_csv(file_name)

# Data Cleaning
df["rate"] = df["rate"].str.extract(r"(\d+\.\d+)").astype(float)

# Display summary statistics
print("Summary Statistics:\n", df.describe(include="all"))

# Visualizations
plt.figure(figsize=(15, 10))

# Subplot 1: Rating Distribution
plt.subplot(2, 2, 1)
sns.histplot(df["rate"], bins=10, kde=True, color="blue")
plt.title("Distribution of Restaurant Ratings")
plt.xlabel("Rating")
plt.ylabel("Count")

# Subplot 2: Online Order Availability
plt.subplot(2, 2, 2)
sns.countplot(data=df, x="online_order", palette="coolwarm")
plt.title("Online Order Availability")
plt.xlabel("Online Order")
plt.ylabel("Count")

# Subplot 3: Customer Votes Distribution
plt.subplot(2, 2, 3)
sns.boxplot(x=df["votes"], color="orange")
plt.title("Distribution of Customer Votes")
plt.xlabel("Votes")

# Subplot 4: Cost Distribution
plt.subplot(2, 2, 4)
sns.histplot(df["approx_cost(for two people)"], bins=10, kde=True, color="green")
plt.title("Distribution of Approximate Cost for Two People")
plt.xlabel("Cost (₹)")
plt.ylabel("Count")

plt.tight_layout()
plt.show()

# Correlation Analysis
correlation_matrix = df[["rate", "votes", "approx_cost(for two people)"]].corr()
print("\nCorrelation Matrix:\n", correlation_matrix)

# Heatmap for correlation
plt.figure(figsize=(8, 5))
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Correlation Heatmap")
plt.show()